name: iris_env
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - numpy
  - pandas
  - scikit-learn=1.3.2
  - rdkit=2024.03.2
  - joblib
  - tqdm
  - biopython
  - plotly
  - numba
  - scipy
  - h5py
  - pycairo
  - pygobject
  - protobuf
  - requests
  - werkzeug
  - termcolor
  - six
  - threadpoolctl
  - openbabel=3.1.1.1

